### ISSUE TITLE
Sort out "not in 'HEAD~1" messages

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/git-whosonfirst-data#16]
INFO:root:copy /usr/local/data/whosonfirst-data-venue-ca/meta/wof-venue-ca-20170106.csv to /usr/local/data/whosonfirst-data-venue-ca/meta/wof-venue-ca-latest.csv
fatal: Path 'data/110/879/869/7/1108798697.geojson' exists on disk, but not in 'HEAD~1'.

**Comment by stepps00** [comment]
Received the following error when trying to commit a new file to Who's On First in a local branch. The full error message was:

```
WARNING:root:PLEASE STOP IMPORTING mapzen.whosonfirst.concordances and USE mapzen.whosonfirst.concordances.pgsql INSTEAD
fatal: Path 'data/110/880/012/3/1108800123.geojson' exists on disk, but not in 'HEAD~1'.
WARNING:root:failed generate report for 110/880/012/3/1108800123.geojson, because Command '['git', '-C', '/usr/local/mapzen/whosonfirst-data', 'show', 'HEAD~1:data/110/880/012/3/1108800123.geojson']' returned non-zero exit status 128
fatal: Path 'data/110/880/012/3/1108800123.geojson' exists on disk, but not in 'HEAD'.
WARNING:root:failed generate report for 110/880/012/3/1108800123.geojson, because Command '['git', '-C', '/usr/local/mapzen/whosonfirst-data', 'show', 'HEAD:data/110/880/012/3/1108800123.geojson']' returned non-zero exit status 128
WARNING:root:failed to generate report for /usr/local/mapzen/whosonfirst-data/data/110/880/012/3/1108800123.geojson, because Failed to generate a report for 110/880/012/3/1108800123.geojson (using HEAD~1 and HEAD)
```

The error is coming from the `concordances.py` script, [here](https://github.com/whosonfirst/git-whosonfirst-data/blob/master/lib/wof/concordances.py#L25-L38). The script is taking the new `wof:id` (unknown to WOF) and trying to find that file in the `whosonfirst-data/data` directory, and because it's a new id, I receive the `logging.warning`. 

If the path to an `id` is not found, instead of throwing up a `logging.warning`, the feature should be written as a new line in the meta file.

**Comment by thisisaaronland** [comment]
@stepps00 - can you paste the contents of this command in to the issue:

`ls -al  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ | grep mapzen`

I am wondering whether you don't have an older version of (some library...) that is causing the problem.

**Comment by stepps00** [comment]
@thisisaaronland - running that yielded no results, my filepath is different than the one listed above.

Running `ls -al /Library/Python/2.7/site-packages | grep mapzen` yielded:

```
mapzen.whosonfirst-0.521-py2.7.egg
mapzen.whosonfirst-0.54_-py2.7.egg
mapzen.whosonfirst-0.70_-py2.7.egg
mapzen.whosonfirst-0.71_-py2.7.egg
mapzen.whosonfirst-0.76_-py2.7.egg
mapzen.whosonfirst-0.93_-py2.7.egg
mapzen.whosonfirst-0.951_-py2.7.egg
mapzen.whosonfirst-0.979_-py2.7.egg
mapzen.whosonfirst.api-0.01_-py2.7.egg
mapzen.whosonfirst.aws-0.2_-py2.7.egg
mapzen.whosonfirst.bundles-0.06-py2.7.egg
mapzen.whosonfirst.bundles-0.061-py2.7.egg
mapzen.whosonfirst.chatterbox-0.1-py2.7.egg
mapzen.whosonfirst.concordances-0.06_-py2.7.egg
mapzen.whosonfirst.diff-0.03_-py2.7.egg
mapzen.whosonfirst.diff-0.05_-py2.7.egg
mapzen.whosonfirst.diff-0.07_-py2.7.egg
mapzen.whosonfirst.elasticsearch-0.025_-py2.7.egg
mapzen.whosonfirst.export-0.75_-py2.7.egg
mapzen.whosonfirst.export-0.791_-py2.7.egg
mapzen.whosonfirst.export-0.79_-py2.7.egg
mapzen.whosonfirst.geojson-0.06_-py2.7.egg
mapzen.whosonfirst.geojson-0.07_-py2.7.egg
mapzen.whosonfirst.git-0.01_-py2.7.egg
mapzen.whosonfirst.git-0.05_-py2.7.egg
mapzen.whosonfirst.git-0.065_-py2.7.egg
mapzen.whosonfirst.languages-0.02_-py2.7.egg
mapzen.whosonfirst.languages-0.04-py2.7.egg
mapzen.whosonfirst.machinetag-0.06_-py2.7.egg
mapzen.whosonfirst.mapshaper-0.05_-py2.7.egg
mapzen.whosonfirst.mapshaper-0.06_-py2.7.egg
mapzen.whosonfirst.meta-0.11_-py2.7.egg
mapzen.whosonfirst.meta-0.12_-py2.7.egg
mapzen.whosonfirst.meta-0.14_-py2.7.egg
mapzen.whosonfirst.names-0.02_-py2.7.egg
mapzen.whosonfirst.pip-0.03_-py2.7.egg
mapzen.whosonfirst.pip-0.04_-py2.7.egg
mapzen.whosonfirst.pip-0.081_-py2.7.egg
mapzen.whosonfirst.pip.utils-0.06-py2.7.egg
mapzen.whosonfirst.pip.utils-0.09-py2.7.egg
mapzen.whosonfirst.placetypes-0.14_-py2.7.egg
mapzen.whosonfirst.placetypes-0.24_-py2.7.egg
mapzen.whosonfirst.placetypes.utils-0.01_-py2.7.egg
mapzen.whosonfirst.search-0.13_-py2.7.egg
mapzen.whosonfirst.search-0.14_-py2.7.egg
mapzen.whosonfirst.search-0.171_-py2.7.egg
mapzen.whosonfirst.search-0.182_-py2.7.egg
mapzen.whosonfirst.search-0.184_-py2.7.egg
mapzen.whosonfirst.search-0.201_-py2.7.egg
mapzen.whosonfirst.sources-0.03_-py2.7.egg
mapzen.whosonfirst.sources-0.063_-py2.7.egg
mapzen.whosonfirst.sources-0.064_-py2.7.egg
mapzen.whosonfirst.sources-0.066_-py2.7.egg
mapzen.whosonfirst.uri-0.1-py2.7.egg
mapzen.whosonfirst.uri-0.2_-py2.7.egg
mapzen.whosonfirst.uri-0.311_-py2.7.egg
mapzen.whosonfirst.utils-0.24_-py2.7.egg
mapzen.whosonfirst.utils-0.25_-py2.7.egg
mapzen.whosonfirst.utils-0.26_-py2.7.egg
mapzen.whosonfirst.utils-0.29_-py2.7.egg
mapzen.whosonfirst.utils-0.30_-py2.7.egg
mapzen.whosonfirst.utils-0.34_-py2.7.egg
mapzen.whosonfirst.utils-0.35_-py2.7.egg
mapzen.whosonfirst.utils-0.381_-py2.7.egg
mapzen.whosonfirst.utils-0.38_-py2.7.egg
mapzen.whosonfirst.validator-0.10_-py2.7.egg
mapzen.whosonfirst.validator-0.12_-py2.7.egg
```

**Comment by thisisaaronland** [comment]
It happened again:

```
INFO:root:append /usr/local/mapzen/acope/git-whosonfirst-data/lib to path
INFO:root:invoking git-whosonfirst-mapzen pre-commit hooks for whatever is different from 873f6670075366b54aaf8d556e58d0de210a4198
INFO:root:git diff --pretty=format: --name-only 873f6670075366b54aaf8d556e58d0de210a4198
INFO:root:invoking hooks on 2 possible files
INFO:root:filtered for wof documents yields 2 possible files
INFO:root:validating /usr/local/data/whosonfirst-data-venue-us-ca/data/110/880/080/3/1108800803.geojson
INFO:root:validating /usr/local/data/whosonfirst-data-venue-us-ca/data/572/190/077/572190077.geojson
INFO:root:validating /usr/local/data/whosonfirst-data-venue-us-ca/data/110/880/080/3/1108800803.geojson
INFO:root:validating /usr/local/data/whosonfirst-data-venue-us-ca/data/572/190/077/572190077.geojson
INFO:root:rebuild meta file for placetype venue with 2 updates
INFO:root:copy /usr/local/data/whosonfirst-data-venue-us-ca/meta/wof-venue-us-ca-20170114.csv to /usr/local/data/whosonfirst-data-venue-us-ca/meta/wof-venue-us-ca-latest.csv
fatal: Path 'data/110/880/080/3/1108800803.geojson' exists on disk, but not in 'HEAD~1'.
WARNING:root:failed generate report for 110/880/080/3/1108800803.geojson, because Command '['git', '-C', '/usr/local/data/whosonfirst-data-venue-us-ca', 'show', 'HEAD~1:data/110/880/080/3/1108800803.geojson']' returned non-zero exit status 128
fatal: Path 'data/110/880/080/3/1108800803.geojson' exists on disk, but not in 'HEAD'.
WARNING:root:failed generate report for 110/880/080/3/1108800803.geojson, because Command '['git', '-C', '/usr/local/data/whosonfirst-data-venue-us-ca', 'show', 'HEAD:data/110/880/080/3/1108800803.geojson']' returned non-zero exit status 128
WARNING:root:failed to generate report for /usr/local/data/whosonfirst-data-venue-us-ca/data/110/880/080/3/1108800803.geojson, because Failed to generate a report for 110/880/080/3/1108800803.geojson (using HEAD~1 and HEAD)
INFO:root:count updated: 2 count updated w/ updated concordances: 1
ERROR:root:Unable to find source file for concordances, expected /usr/local/data/whosonfirst-data-venue-us-ca/meta/wof-concordances-latest.csv BUT IT'S NOT THERE
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 104, in <module>
    modified, created = wof.common.update_ancillary_files(base, updated)
  File "/usr/local/mapzen/acope/git-whosonfirst-data/lib/wof/common.py", line 83, in update_ancillary_files
    for path in _modified:
TypeError: 'NoneType' object is not iterable
```

**Comment by thisisaaronland** [comment]
Who/what is trying to `HEAD~1`? I can't find any explicit invocation of that in the code...

**Comment by thisisaaronland** [comment]
Notes to self.

Things like this `fatal: Path 'data/110/880/080/3/1108800803.geojson' exists on disk, but not in 'HEAD~1'.` happen here:

```
grep -n -r -e 'failed to generate' ./
./lib/wof/concordances.py:38:            logging.warning("failed to generate report for %s, because %s" % (path, e))
```

Which is part of this:

```
        try:
            report = diff.report(id)
            if report['concordances'] == True:
```

Which suggests that py-mz-wof-diff needs to be updated to actually check that a file exists but ultimately this is just a warning.

The actual fatal error:

```
ERROR:root:Unable to find source file for concordances, expected /usr/local/data/whosonfirst-data-venue-us-ca/meta/wof-concordances-latest.csv BUT IT'S NOT THERE
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 104, in <module>
    modified, created = wof.common.update_ancillary_files(base, updated)
  File "/usr/local/mapzen/acope/git-whosonfirst-data/lib/wof/common.py", line 83, in update_ancillary_files
    for path in _modified:
TypeError: 'NoneType' object is not iterable
```
Should be fixed as of https://github.com/whosonfirst/git-whosonfirst-data/issues/17#issuecomment-273582437 but needs to be tested more.
