### ISSUE TITLE
Don't panic when -latest.csv meta files are missing

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/git-whosonfirst-data#17]
```
git commit -m "update Pied de Cochon" .
/usr/local/lib/python2.7/dist-packages/urllib3-1.19-py2.7.egg/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3-1.19-py2.7.egg/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
INFO:root:append /usr/local/mapzen/acope/git-whosonfirst-data/lib to path
INFO:root:invoking git-whosonfirst-mapzen pre-commit hooks for whatever is different from 37c7627a5e2ff806ca78f8d569e9a06f999635c3
INFO:root:git diff --pretty=format: --name-only 37c7627a5e2ff806ca78f8d569e9a06f999635c3
INFO:root:invoking hooks on 1 possible files
INFO:root:filtered for wof documents yields 1 possible files
INFO:root:validating /usr/local/data/whosonfirst-data-venue-ca/data/203/347/807/203347807.geojson
INFO:root:validating /usr/local/data/whosonfirst-data-venue-ca/data/203/347/807/203347807.geojson
INFO:root:rebuild meta file for placetype venue with one update
INFO:root:copy /usr/local/data/whosonfirst-data-venue-ca/meta/wof-venue-ca-20170118.csv to /usr/local/data/whosonfirst-data-venue-ca/meta/wof-venue-ca-latest.csv
INFO:root:count updated: 1 count updated w/ updated concordances: 1
ERROR:root:Unable to find source file for concordances, expected /usr/local/data/whosonfirst-data-venue-ca/meta/wof-concordances-latest.csv BUT IT'S NOT THERE
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 104, in <module>
    modified, created = wof.common.update_ancillary_files(base, updated)
  File "/usr/local/mapzen/acope/git-whosonfirst-data/lib/wof/common.py", line 83, in update_ancillary_files
    for path in _modified:
TypeError: 'NoneType' object is not iterable
```

**Comment by thisisaaronland** [comment]
Careful observers will note that the code is expecting the old format for filenames...

```
ll meta
total 673840
-rw-r--r-- 1 wof mapzen          30 Jan  5 22:43 .gitignore
-rw-r--r-- 1 wof mapzen   162285893 Jan  5 23:10 wof-venue-ca-20170105.csv
-rw-r--r-- 1 wof mapzen   162286723 Jan  6 20:02 wof-venue-ca-20170106.csv
-rw-r--r-- 1 wof mapzen   162286723 Jan 18 01:33 wof-venue-ca-20170118.csv
-rw-r--r-- 1 wof opsworks  40849725 Jan  5 22:45 wof-venue-ca-concordances-latest.csv
-rw-r--r-- 1 wof opsworks 162286723 Jan 18 01:33 wof-venue-ca-latest.csv
```

**Comment by thisisaaronland** [comment]
Should be fixed in https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/commit/a38cf294d71b24d0008a78e08961927759c86b57 but still needs testing.
